theme = "ghostwriter"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "bangtedy Blog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true