theme = "ghostwriter"
baseURL = "https://bangtedy.rbind.io/"
languageCode = "en-us"
title = "My New Hugo Site"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
