<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="generator" content="Hugo 0.74.3 with theme Tranquilpeak 0.4.8-BETA">
<meta name="author" content="Tedy Herlambang">
<meta name="keywords" content="">
<meta name="description" content="Bergegaslah bangun dari mimpi
Atau engkau akan kehilangan
Ebit G Ade
Keuntungan. Ya, keuntungan yang diharapkan bisa lenyap jika tidak gegas dan cermat dalam mengambil keputusan di bursa saham. Ketika pasar masih mencoba mencerna dan menduga-duga, seorang profesional dengan keterampilan dan pengalamannya malah sudah mengantisipasinya.
Sebagai mahasiswa agribisnis, kita harus “kepo” terhadap segala informasi, data dan kejadian-kejadian yang akan berdampak langsung/tidak langsung pada sektor agribisnis dimana kita adalah bagian di dalamnya.">


<meta property="og:description" content="Bergegaslah bangun dari mimpi
Atau engkau akan kehilangan
Ebit G Ade
Keuntungan. Ya, keuntungan yang diharapkan bisa lenyap jika tidak gegas dan cermat dalam mengambil keputusan di bursa saham. Ketika pasar masih mencoba mencerna dan menduga-duga, seorang profesional dengan keterampilan dan pengalamannya malah sudah mengantisipasinya.
Sebagai mahasiswa agribisnis, kita harus “kepo” terhadap segala informasi, data dan kejadian-kejadian yang akan berdampak langsung/tidak langsung pada sektor agribisnis dimana kita adalah bagian di dalamnya.">
<meta property="og:type" content="article">
<meta property="og:title" content="Kandil Pertanian">
<meta name="twitter:title" content="Kandil Pertanian">
<meta property="og:url" content="/2020/08/saham-agro/">
<meta property="twitter:url" content="/2020/08/saham-agro/">
<meta property="og:site_name" content="Hugo tranquilpeak theme">
<meta property="og:description" content="Bergegaslah bangun dari mimpi
Atau engkau akan kehilangan
Ebit G Ade
Keuntungan. Ya, keuntungan yang diharapkan bisa lenyap jika tidak gegas dan cermat dalam mengambil keputusan di bursa saham. Ketika pasar masih mencoba mencerna dan menduga-duga, seorang profesional dengan keterampilan dan pengalamannya malah sudah mengantisipasinya.
Sebagai mahasiswa agribisnis, kita harus “kepo” terhadap segala informasi, data dan kejadian-kejadian yang akan berdampak langsung/tidak langsung pada sektor agribisnis dimana kita adalah bagian di dalamnya.">
<meta name="twitter:description" content="Bergegaslah bangun dari mimpi
Atau engkau akan kehilangan
Ebit G Ade
Keuntungan. Ya, keuntungan yang diharapkan bisa lenyap jika tidak gegas dan cermat dalam mengambil keputusan di bursa saham. Ketika pasar masih mencoba mencerna dan menduga-duga, seorang profesional dengan keterampilan dan pengalamannya malah sudah mengantisipasinya.
Sebagai mahasiswa agribisnis, kita harus “kepo” terhadap segala informasi, data dan kejadian-kejadian yang akan berdampak langsung/tidak langsung pada sektor agribisnis dimana kita adalah bagian di dalamnya.">
<meta property="og:locale" content="en-us">

  
    <meta property="article:published_time" content="2020-08-29T00:00:00">
  
  
    <meta property="article:modified_time" content="2020-08-29T00:00:00">
  
  
  
    
      <meta property="article:section" content="finance">
    
  
  
    
      <meta property="article:tag" content="keuangan">
    
      <meta property="article:tag" content="saham">
    
      <meta property="article:tag" content="finance">
    
      <meta property="article:tag" content="candlestick">
    
  


<meta name="twitter:card" content="summary">











  <meta property="og:image" content="https://www.gravatar.com/avatar/4b3012f5af5ade5b7f63190b5a5401e5?s=640">
  <meta property="twitter:image" content="https://www.gravatar.com/avatar/4b3012f5af5ade5b7f63190b5a5401e5?s=640">


    <title>Kandil Pertanian</title>

    <link rel="icon" href="/favicon.png">
    

    

    <link rel="canonical" href="/2020/08/saham-agro/">

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="/css/style-twzjdbqhmnnacqs0pwwdzcdbt8yhv8giawvjqjmyfoqnvazl0dalmnhdkvp7.min.css" />
    
    

    
      
    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="4">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="/">Hugo tranquilpeak theme</a>
  </div>
  
    
      <a class="header-right-picture "
         href="/#about">
    
    
    
      
        <img class="header-picture" src="https://www.gravatar.com/avatar/4b3012f5af5ade5b7f63190b5a5401e5?s=90" alt="Author&#39;s picture" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="4">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="/#about">
          <img class="sidebar-profile-picture" src="https://www.gravatar.com/avatar/4b3012f5af5ade5b7f63190b5a5401e5?s=110" alt="Author&#39;s picture" />
        </a>
        <h4 class="sidebar-profile-name">Tedy Herlambang</h4>
        
          <h5 class="sidebar-profile-bio">Macul with markdown support <strong>CUL</strong></h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Home</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categories</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      
      <span class="sidebar-button-desc">Tags</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      
      <span class="sidebar-button-desc">Archives</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/#about">
    
      <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      
      <span class="sidebar-button-desc">About</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/kakawait">
    
      <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://stackoverflow.com/users/636472/kakawait">
    
      <i class="sidebar-button-icon fa fa-lg fa-stack-overflow"></i>
      
      <span class="sidebar-button-desc">Stack Overflow</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/index.xml">
    
      <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      
      <span class="sidebar-button-desc">RSS</span>
    </a>
  </li>


    </ul>
  </div>
</nav>

      

      <div id="main" data-behavior="4"
        class="
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Kandil Pertanian
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2020-08-29T00:00:00Z">
        
  August 29, 2020

      </time>
    
    
  
  
    <span>in</span>
    
      <a class="category-link" href="/categories/finance">finance</a>
    
  

  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              


<p><em>Bergegaslah bangun dari mimpi</em></p>
<p><em>Atau engkau akan kehilangan</em></p>
<p><strong>Ebit G Ade</strong></p>
<p>Keuntungan. Ya, keuntungan yang diharapkan bisa lenyap jika tidak gegas dan cermat dalam mengambil keputusan di bursa saham. Ketika pasar masih mencoba mencerna dan menduga-duga, seorang profesional dengan keterampilan dan pengalamannya malah sudah mengantisipasinya.</p>
<p>Sebagai mahasiswa agribisnis, kita harus “kepo” terhadap segala informasi, data dan kejadian-kejadian yang akan berdampak langsung/tidak langsung pada sektor agribisnis dimana kita adalah bagian di dalamnya. Okey Gaes, kali ini kita akan belajar melihat pergerakan harga saham salah satu perusahaan yang bergerak di bidang pembiayaan agribisnis.</p>
<p>Bursa saham sebagai bagian dari pasar keuangan berperan penting dalam kapitalisme untuk mempertemukan sektor riil dengan sektor keuangan. Ada tulisan menarik tentang COVID-19 yang konon mempercepat transisi dari <em>capitalism</em> ke <em>postcapitalism</em> sehingga terjadi <em>disconnection</em> antara ekonomi riil dengan ekonomi keuangan yang bisa dibaca di <a href="https://www.nakedcapitalism.com/2020/08/something-remarkable-just-happened-this-august-how-the-pandemic-has-sped-up-the-passage-to-postcapitalism.html">naked capitalism</a>.</p>
<p>Sebagai mahasiswa yang kemungkinan nanti juga akan terjun ke dunia persahaman, tidak ada salahnya jika kita mempersiapkan diri. Salah satu keterampilan yang diperlukan di bursa saham adalah keterampilan analisis. Agar bisa menganalisis pertama harus belajar alat analisisnya.</p>
<p>Kemampuan analisis adalah keterampilan dasar yang diperlukan di pasar saham sehingga seseorang bisa memahami, mengidentifikasi dan memanfaatkan peluang untuk memperolah keuntungan. Ketika sudah masuk kesini, seseorang harus mempersiapkan diri termasuk untuk kemungkinan buruk, selalu menjaga kewarasan dan tidak gampang panik dan putus asa. Sudah banyak cerita orang terjun dari lantai 10 karena salah “mainnya”. Panik bisa membuat keputusan yang sudah keliru menjadi lebih buruk lagi ya khan?</p>
<p>Dengan mempelajari teknik dasar analisis, mencermati pergerakan harga dalam waktu yang cukup, seseorang akan dapat “merasakan” pasang surut, naik-turunnya harga, dan akan sangat membantu seseorang untuk belajar dan membuat penyesuaian yang diperlukan dalam perdagangan. Setelah itu kita dapat mencoba melatih intuisi dengan memprediksi perubahan harga.</p>
<p>Secara teori, sekuritas (<em>stock, bond, option</em>) hanya dapat menjadi lebih tinggi atau lebih rendah. Tetapi di dalam kenyataannya, harga-harga dapat berubah semaunya sendiri. Di dalam kondisi gonjang-ganjing ini, untung atau buntung. Kita dapat mengamati pergerakan saham dari menit per menit, jam-jaman, harian, mingguan atau bulanan.</p>
<p>Kali ini kita akan mencoba belajar tentang hal ini. Situs-situs untuk belajar bursa saham banyak, diantaranya <a href="https://www.sahamok.com/">sahamok.com</a>, yang berbahasa Inggris bisa melihat <a href="https://www.morningstar.com/">Morningstar</a>.</p>
<p>Salah situs yang menyediakan data historis dan bisa diunduh misalnya <a href="https://finance.yahoo.com/">Yahoo Finance</a>. Data di Yahoo Finance mencakup harga pembukaan (open), harga tinggi (high), harga rendah (low), harga penutupan (close) dan volume perdagangan. Silakan dibaca tentang istilah-istilah ini, misalnya <a href="https://www.investopedia.com/">disini</a>.</p>
<div id="mengunduh-data" class="section level2">
<h2>Mengunduh data</h2>
<p>Kita akan unduh data dari <em>Yahoo Finance</em> langsung ke dalam R dengan paket <em>quantmod</em>. Kita instal dulu paket ini dengan perintah install.packages(“quantmod”). Setelah terpasang kita panggil dengan perintah:</p>
<pre class="r"><code>library(quantmod) #untuk memanggil paket quantmod</code></pre>
<pre><code>## Loading required package: xts</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre><code>## Loading required package: TTR</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre><code>## Version 0.4-0 included new data defaults. See ?getSymbols.</code></pre>
<p>Selanjutnya Kita akan mengambil data salah satu perusahaan yang go public dan berhubungan dengan agribisnis yaitu PT Bank Rakyat Indonesia Agroniaga Tbk, dengan ticker AGRO.JK. Datanya kita beri nama data.AGRO dan diunduh dengan perintah getSymbols:</p>
<pre class="r"><code>data.AGRO &lt;- getSymbols(&quot;AGRO.JK&quot;,from=&quot;2017-08-01&quot;, to=&quot;2020-08-01&quot;, auto.assign=FALSE) #kita unduh data 3 tahun terakhir dari 1 Agt 2017 - 1 Agt 2020.</code></pre>
<pre><code>## &#39;getSymbols&#39; currently uses auto.assign=TRUE by default, but will
## use auto.assign=FALSE in 0.5-0. You will still be able to use
## &#39;loadSymbols&#39; to automatically load data. getOption(&quot;getSymbols.env&quot;)
## and getOption(&quot;getSymbols.auto.assign&quot;) will still be checked for
## alternate defaults.
## 
## This message is shown once per session and may be disabled by setting 
## options(&quot;getSymbols.warning4.0&quot;=FALSE). See ?getSymbols for details.</code></pre>
</div>
<div id="untuk-melihat-nama-nama-variabel-yang-diunduh" class="section level2">
<h2>Untuk melihat nama-nama variabel yang diunduh</h2>
<pre class="r"><code>names(data.AGRO)</code></pre>
<pre><code>## [1] &quot;AGRO.JK.Open&quot;     &quot;AGRO.JK.High&quot;     &quot;AGRO.JK.Low&quot;      &quot;AGRO.JK.Close&quot;   
## [5] &quot;AGRO.JK.Volume&quot;   &quot;AGRO.JK.Adjusted&quot;</code></pre>
<p>Terlihat bahwa data yang kita unduh terdiri dari 6 kolom (7 kolom dengan tanggal) terdiri AGRO.JK.Open menunjukkan harga pembukaan, AGRO.JK.High menunjukkan harga tertinggi, dan seterusnya.</p>
</div>
<div id="untuk-melihat-dimensi-data" class="section level2">
<h2>Untuk melihat dimensi data</h2>
<pre class="r"><code>dim(data.AGRO) </code></pre>
<pre><code>## [1] 771   6</code></pre>
<p>Data yang kita unduh adalah 771 hari</p>
</div>
<div id="untuk-melihat-ringkasan-data-secara-keseluruhan" class="section level2">
<h2>Untuk melihat ringkasan data secara keseluruhan</h2>
<pre class="r"><code>summary(data.AGRO) </code></pre>
<pre><code>##      Index             AGRO.JK.Open    AGRO.JK.High    AGRO.JK.Low   
##  Min.   :2017-08-01   Min.   : 78.0   Min.   : 88.0   Min.   : 78.0  
##  1st Qu.:2018-04-26   1st Qu.:220.0   1st Qu.:226.0   1st Qu.:216.0  
##  Median :2019-01-22   Median :322.0   Median :326.0   Median :318.0  
##  Mean   :2019-01-23   Mean   :329.3   Mean   :336.5   Mean   :323.7  
##  3rd Qu.:2019-10-17   3rd Qu.:391.0   3rd Qu.:397.0   3rd Qu.:384.0  
##  Max.   :2020-07-30   Max.   :635.0   Max.   :655.0   Max.   :615.0  
##  AGRO.JK.Close   AGRO.JK.Volume      AGRO.JK.Adjusted
##  Min.   : 83.0   Min.   :        0   Min.   : 83.0   
##  1st Qu.:220.0   1st Qu.:  1966800   1st Qu.:220.0   
##  Median :320.0   Median :  4036900   Median :320.0   
##  Mean   :328.2   Mean   : 11903487   Mean   :325.9   
##  3rd Qu.:384.0   3rd Qu.:  9780350   3rd Qu.:381.7   
##  Max.   :630.0   Max.   :292992500   Max.   :621.9</code></pre>
<p>Menunjukkan data minimum, maksimum, rata-rata, median dan kuartil.
Sekarang kita akan mengeksplorasi data yang sudah diunduh, dengan perintah-perintah berikut:</p>
</div>
<div id="untuk-melihat-data-pertama-dan-terakhir-yang-diunduh" class="section level2">
<h2>Untuk melihat data pertama dan terakhir yang diunduh</h2>
<pre class="r"><code>data.AGRO[c(1,nrow(data.AGRO)),] </code></pre>
<pre><code>##            AGRO.JK.Open AGRO.JK.High AGRO.JK.Low AGRO.JK.Close AGRO.JK.Volume
## 2017-08-01          605          615         565           580       28088400
## 2020-07-30          240          248         228           232       75788800
##            AGRO.JK.Adjusted
## 2017-08-01         572.5104
## 2020-07-30         232.0000</code></pre>
</div>
<div id="untuk-melihat-data-pada-lima-hari-minggu-pertama-agustus-2017" class="section level2">
<h2>Untuk melihat data pada lima hari minggu pertama Agustus 2017</h2>
<pre class="r"><code>AGRO.first.week &lt;- data.AGRO[1:5,] 
AGRO.first.week</code></pre>
<pre><code>##            AGRO.JK.Open AGRO.JK.High AGRO.JK.Low AGRO.JK.Close AGRO.JK.Volume
## 2017-08-01          605          615         565           580       28088400
## 2017-08-02          525          585         510           525       75341000
## 2017-08-03          525          555         505           515       57185900
## 2017-08-04          520          535         515           525       24427000
## 2017-08-07          530          585         520           565       93131900
##            AGRO.JK.Adjusted
## 2017-08-01         572.5104
## 2017-08-02         518.2207
## 2017-08-03         508.3498
## 2017-08-04         518.2207
## 2017-08-07         557.7041</code></pre>
</div>
<div id="untuk-data-perdagangan-pada-30-hari-terakhir" class="section level2">
<h2>Untuk data perdagangan pada 30 hari terakhir</h2>
<pre class="r"><code>AGRO.last30 &lt;-data.AGRO[((nrow(data.AGRO)-29)):nrow(data.AGRO),] 
AGRO.last30</code></pre>
<pre><code>##            AGRO.JK.Open AGRO.JK.High AGRO.JK.Low AGRO.JK.Close AGRO.JK.Volume
## 2020-06-19          131          132         125           127        8994500
## 2020-06-22          129          129         124           125        9552000
## 2020-06-23          124          127         122           123        5275900
## 2020-06-24          123          129         120           125        8807600
## 2020-06-25          125          125         121           123        5534300
## 2020-06-26          125          126         122           123        8477500
## 2020-06-29          123          126         123           123        5337900
## 2020-06-30          124          125         122           122        3854700
## 2020-07-01          123          124         121           123        2556000
## 2020-07-02          123          125         123           123        3779400
## 2020-07-03          123          129         121           125       20239500
## 2020-07-06          130          153         125           151      190823700
## 2020-07-07          155          167         144           151      247830800
## 2020-07-08          157          158         145           146       47263700
## 2020-07-09          149          150         141           143       35523400
## 2020-07-10          143          159         140           150      154114800
## 2020-07-13          150          156         150           154       33698800
## 2020-07-14          154          206         152           206      285128200
## 2020-07-15          218          248         214           224      292992500
## 2020-07-16          220          234         216           222       57949200
## 2020-07-17          222          238         218           228      116634100
## 2020-07-20          230          232         218           220       39145200
## 2020-07-21          226          228         218           222       21424600
## 2020-07-22          222          226         218           220       28025400
## 2020-07-23          222          244         222           230      132622100
## 2020-07-24          230          232         216           220       38167300
## 2020-07-27          220          226         218           220       16876100
## 2020-07-28          222          268         218           258      278212500
## 2020-07-29          262          264         240           240      112999300
## 2020-07-30          240          248         228           232       75788800
##            AGRO.JK.Adjusted
## 2020-06-19              127
## 2020-06-22              125
## 2020-06-23              123
## 2020-06-24              125
## 2020-06-25              123
## 2020-06-26              123
## 2020-06-29              123
## 2020-06-30              122
## 2020-07-01              123
## 2020-07-02              123
## 2020-07-03              125
## 2020-07-06              151
## 2020-07-07              151
## 2020-07-08              146
## 2020-07-09              143
## 2020-07-10              150
## 2020-07-13              154
## 2020-07-14              206
## 2020-07-15              224
## 2020-07-16              222
## 2020-07-17              228
## 2020-07-20              220
## 2020-07-21              222
## 2020-07-22              220
## 2020-07-23              230
## 2020-07-24              220
## 2020-07-27              220
## 2020-07-28              258
## 2020-07-29              240
## 2020-07-30              232</code></pre>
<p>Jika kita ingin membandingkan harga pembukaan dan penutupan harian dari saham BRI Agro, berarti kita hanya ingin melihat data di kolom 1 dan kolom 4 saja. Maka kita menggunakan operator c(1,4) untuk melihat kedua kolom tersebut.</p>
</div>
<div id="melihat-harga-pembukaan-dan-penutupan" class="section level2">
<h2>Melihat harga pembukaan dan penutupan</h2>
<pre class="r"><code>AGRO.OpenClose &lt;- data.AGRO[,c(1,4)] 
AGRO.OpenClose[c(1:5,nrow(AGRO.OpenClose)),] #melihat data di 5 baris pertama dan 1 baris terakhir.</code></pre>
<pre><code>##            AGRO.JK.Open AGRO.JK.Close
## 2017-08-01          605           580
## 2017-08-02          525           525
## 2017-08-03          525           515
## 2017-08-04          520           525
## 2017-08-07          530           565
## 2020-07-30          240           232</code></pre>
</div>
<div id="melihat-data-harga-penutupan-dan-volume-perdagangan" class="section level2">
<h2>Melihat data harga penutupan dan volume perdagangan</h2>
<pre class="r"><code>AGRO.PriceVol &lt;- data.AGRO[,4:5] 
AGRO.PriceVol[c(1:5,nrow(AGRO.PriceVol)),] #melihat data di 5 baris pertama dan 1 baris terakhir data harga dan volume perdagangan.</code></pre>
<pre><code>##            AGRO.JK.Close AGRO.JK.Volume
## 2017-08-01           580       28088400
## 2017-08-02           525       75341000
## 2017-08-03           515       57185900
## 2017-08-04           525       24427000
## 2017-08-07           565       93131900
## 2020-07-30           232       75788800</code></pre>
</div>
<div id="melihat-data-harga-pembukaan-penutupan-dan-volume-perdagangan" class="section level2">
<h2>Melihat data harga pembukaan, penutupan dan volume perdagangan</h2>
<pre class="r"><code>AGRO.OpenCloseVol&lt;-data.AGRO[,c(1,4:5)] 
AGRO.OpenCloseVol[c(1:3,nrow(AGRO.OpenCloseVol)),] #melihat data di 5 baris pertama dan 1 baris terakhir data harga pembukaan, penutupan dan volume perdagangan.</code></pre>
<pre><code>##            AGRO.JK.Open AGRO.JK.Close AGRO.JK.Volume
## 2017-08-01          605           580       28088400
## 2017-08-02          525           525       75341000
## 2017-08-03          525           515       57185900
## 2020-07-30          240           232       75788800</code></pre>
<p>Data harian yang tadi sudah di unduh, bisa diubah menjadi data mingguan dan bulanan.</p>
</div>
<div id="mengubah-ke-data-mingguan" class="section level2">
<h2>Mengubah ke data mingguan</h2>
<pre class="r"><code>week&lt;-data.AGRO 
data.weekly&lt;-to.weekly(week)
data.weekly[c(1:5,nrow(data.weekly)),] #melihat data di 5 minggu pertama dan 1 minggu terakhir.</code></pre>
<pre><code>##            week.Open week.High week.Low week.Close week.Volume week.Adjusted
## 2017-08-04       605       615      505        525   185042300      518.2207
## 2017-08-11       530       615      520        565   266636100      557.7041
## 2017-08-18       565       585      555        560    44057600      552.7687
## 2017-08-25       565       580      540        545    94484600      537.9624
## 2017-09-01       545       560      510        510    99493700      503.4143
## 2020-07-30       220       268      218        232   483876700      232.0000</code></pre>
</div>
<div id="mengubah-ke-data-bulanan" class="section level2">
<h2>Mengubah ke data bulanan</h2>
<pre class="r"><code>month&lt;-data.AGRO 
data.monthly&lt;-to.monthly(month)
data.monthly[c(1:5,nrow(data.monthly)),] #melihat data di 5 bulan pertama dan 1 bulan terakhir.</code></pre>
<pre><code>##          month.Open month.High month.Low month.Close month.Volume
## Aug 2017        605        615       505         510    689714300
## Sep 2017        510        655       482         615    813728300
## Oct 2017        615        625       530         535    395699900
## Nov 2017        540        595       520         535    317275900
## Dec 2017        535        545       500         525     99265900
## Jul 2020        123        268       121         232   2231795400
##          month.Adjusted
## Aug 2017       503.4143
## Sep 2017       607.0585
## Oct 2017       528.0915
## Nov 2017       528.0915
## Dec 2017       518.2207
## Jul 2020       232.0000</code></pre>
</div>
<div id="ploting-harga-penutupan" class="section level2">
<h2>Ploting harga penutupan</h2>
<p>Salah satu data yang perlu dicermati adalah harga penutupan. Investor, pialang, lembaga keuangan, dan regulator menggunakan harga penutupan sebagai indikator untuk menentukan kinerja suatu saham dalam jangka waktu tertentu. Ploting harga penutupan bisa dilakukan dengan perintah berikut:</p>
<pre class="r"><code>plot(data.AGRO$AGRO.JK.Close) #ploting harga penutupan</code></pre>
<p><img src="/post/2020-08-29-saham-agro_files/figure-html/unnamed-chunk-14-1.png" width="672" />
Hmm…ternyata harga penutupan saham Agroniaga dalam 3 tahun terakhir trendnya terus menurun ya, walaupun pada pertengahan tahun 2020 terlihat kembali naik.</p>
</div>
<div id="membuat-grafik-candlestick-dengan-data-bulanan" class="section level2">
<h2>Membuat grafik <em>candlestick</em> dengan data bulanan</h2>
<p>Salah satu grafik yang berguna untuk melihat perbedaan antara harga tertinggi dan terendah, harga pembukaan dan penutupan secara visual adalah dengan membuat <em>candlestick chart</em>. Tentang candlestick bisa dibaca <a href="https://www.soegeeforex.com/tips-dan-trik/belajar-trading-emas-menggunakan-candlestick/">disini</a>. Untuk membuatnya pertama data kita ubah ke dalam bentuk obyek <em>open-high-low-close</em> (OHLC). Perintahnya:</p>
<pre class="r"><code>OHLC&lt;-data.monthly[-1,-6] #kolom pertama dan keenam tidak diikutkan
AGRO.ohlc&lt;-as.quantmod.OHLC(OHLC,col.names=c(&quot;Open&quot;,&quot;High&quot;,&quot;Low&quot;,&quot;Close&quot;,&quot;Volume&quot;))
class(AGRO.ohlc)</code></pre>
<pre><code>## [1] &quot;quantmod.OHLC&quot; &quot;zoo&quot;</code></pre>
<pre class="r"><code>AGRO.ohlc[c(1:3,nrow(AGRO.ohlc)),] #melihat 3 data pertama dan data terakhir</code></pre>
<pre><code>##          OHLC.Open OHLC.High OHLC.Low OHLC.Close OHLC.Volume
## Sep 2017       510       655      482        615   813728300
## Oct 2017       615       625      530        535   395699900
## Nov 2017       540       595      520        535   317275900
## Jul 2020       123       268      121        232  2231795400</code></pre>
<pre class="r"><code>chartSeries(AGRO.ohlc, name=&quot;PT BRI Agroniaga OHLC&quot;) ##perintah membuat candlestick chart</code></pre>
<p><img src="/post/2020-08-29-saham-agro_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Candlestick chart menunjukkan bahwa pada November dan Desember 2018 selisih antara harga tertinggi dan terendah paling kecil. Sedangkan selisih harga terbesar terjadi pada bulan Maret 2018 yaitu harga tertinggi sebesar 565 dan terendah sebesar 412 sehingga terdapat selisih sebesar 153. Btw itu satuan harga sahamnya apa ya? Coba dicek!</p>
<p>Nah, tema grafik bisa kita ubah latar dan warnanya, misalnya untuk keperluan presentasi sehingga kelihatan lebih menarik (lain kali kita akan lakukan). Oke gaes…Selamat belajar, semoga bisa menjadi kandil sektor pertanian.</p>
</div>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">TAGGED IN</span><br/>
                    
  <a class="tag tag--primary tag--small" href="/tags/keuangan/">keuangan</a>

  <a class="tag tag--primary tag--small" href="/tags/saham/">saham</a>

  <a class="tag tag--primary tag--small" href="/tags/finance/">finance</a>

  <a class="tag tag--primary tag--small" href="/tags/candlestick/">candlestick</a>

                  </div>
                
              
            
            <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2020/08/uji-klinis-uji-statistik/" data-tooltip="Uji Klinis Uji Statistik">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2020/08/saham-agro/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2020/08/saham-agro/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2020/08/saham-agro/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  
</div>

            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2020 Tedy Herlambang. All Rights Reserved
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="4">
        <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2020/08/uji-klinis-uji-statistik/" data-tooltip="Uji Klinis Uji Statistik">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2020/08/saham-agro/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2020/08/saham-agro/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2020/08/saham-agro/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  
</div>

      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="4">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?u=%2F2020%2F08%2Fsaham-agro%2F">
          <i class="fa fa-facebook-official"></i><span>Share on Facebook</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=%2F2020%2F08%2Fsaham-agro%2F">
          <i class="fa fa-twitter"></i><span>Share on Twitter</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://plus.google.com/share?url=%2F2020%2F08%2Fsaham-agro%2F">
          <i class="fa fa-google-plus"></i><span>Share on Google&#43;</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="https://www.gravatar.com/avatar/4b3012f5af5ade5b7f63190b5a5401e5?s=110" alt="Author&#39;s picture" />
    
    <h4 id="about-card-name">Tedy Herlambang</h4>
    
      <div id="about-card-bio">Macul with markdown support <strong>CUL</strong></div>
    
    
      <div id="about-card-job">
        <i class="fa fa-briefcase"></i>
        <br/>
        Bercocok tanam
      </div>
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        PP Paiton Probolinggo
      </div>
    
  </div>
</div>

    

    
  
    
      <div id="cover" style="background-image:url('/images/cover.jpg');"></div>
    
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="/js/script-pcw6v3xilnxydl1vddzazdverrnn9ctynvnxgwho987mfyqkuylcb1nlt.min.js"></script>


<script lang="javascript">
window.onload = updateMinWidth;
window.onresize = updateMinWidth;
document.getElementById("sidebar").addEventListener("transitionend", updateMinWidth);
function updateMinWidth() {
  var sidebar = document.getElementById("sidebar");
  var main = document.getElementById("main");
  main.style.minWidth = "";
  var w1 = getComputedStyle(main).getPropertyValue("min-width");
  var w2 = getComputedStyle(sidebar).getPropertyValue("width");
  var w3 = getComputedStyle(sidebar).getPropertyValue("left");
  main.style.minWidth = `calc(${w1} - ${w2} - ${w3})`;
}
</script>

<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = '\/2020\/08\/saham-agro\/';
          
            this.page.identifier = '\/2020\/08\/saham-agro\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'hugo-tranquilpeak-theme';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  




    
  </body>
</html>

