<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Normal di Era New Normal &middot; Tedy Herlambang</title>
        <meta name="description" content="They are like a garden on a hill: heavy rain falls and it produces double its normal yield; Al-Baqarah 2:265
Cuaca yang bersahabat dapat meningkatkan produksi kebun. Sebaliknya cuaca yang tidak mendukung seperti kekeringan dapat menurunkan hasil kebun. Fluktuasi produksi merupakan hal yang normal terutama di pertanian. Pada kondisi yang ekstrim, penurunan dan kenaikan produksi juga bisa ekstrim, jauh dari tingkat “normalnya”.
Di dalam banyak hal, nilai suatu pengukuran (produksi, konsumsi, tinggi badan, tingkat kepuasan,kecerdasan dll) sebagian besar berkumpul pada angka tertentu, kemudian proporsinya semakin mengecil ketika nilai-nilai itu semakin jauh dari nilai pemusatannya (central value).">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta name="generator" content="Hugo 0.75.1" />
        <meta name="robots" content="index,follow">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <link rel="stylesheet" href="/dist/site.css">
        <link rel="stylesheet" href="/dist/syntax.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin,cyrillic-ext,latin-ext,cyrillic">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        
        
        
        
    </head>
    <body>
        

        <div id="wrapper">
            <header class="site-header">
                <div class="container">
                    <div class="site-title-wrapper">
                        
                            <h1 class="site-title">
                                <a title="bangtedy BLOG" href="/">bangtedy BLOG</a>
                            </h1>
                        
                        <a class="button-square" href="/index.xml"><i class="fa fa-rss"></i></a>
                        
                        
                        
                        
                        
                        
                        
                    </div>

                    <ul class="site-nav">
                        
    <li class="site-nav-item">
        <a title="Home" href="/">Home</a>
    </li>

    <li class="site-nav-item">
        <a title="Categories" href="/categories">Categories</a>
    </li>

    <li class="site-nav-item">
        <a title="Tags" href="/tags">Tags</a>
    </li>

    <li class="site-nav-item">
        <a title="Archives" href="/archives">Archives</a>
    </li>

    <li class="site-nav-item">
        <a title="About" href="/#about">About</a>
    </li>

    <li class="site-nav-item">
        <a title="Getting Started with Hugo" href="/2014/04/getting-started-with-hugo/">Getting Started with Hugo</a>
    </li>

                    </ul>
                </div>
            </header>

            <div id="container">


<div class="container">
    <article class="post-container" itemscope="" itemtype="http://schema.org/BlogPosting">
        <header class="post-header">
    <h1 class="post-title" itemprop="name headline">Normal di Era New Normal</h1>
    
    <p class="post-date post-line">
        <span>Published <time datetime="2020-08-15" itemprop="datePublished">Sat, Aug 15, 2020</time></span>
        <span>by</span>
        <span itemscope="" itemprop="author" itemtype="https://schema.org/Person">
            <span itemprop="name">
                <a href="#" itemprop="url" rel="author">Tedy Herlambang</a>
            </span>
        </span>
    </p>
    
</header>

        <div class="post-content clearfix" itemprop="articleBody">
    

    


<p><em>They are like a garden on a hill: heavy rain falls and it produces double its <em>normal</em> yield; Al-Baqarah 2:265</em></p>
<p>Cuaca yang bersahabat dapat meningkatkan produksi kebun. Sebaliknya cuaca yang tidak mendukung seperti kekeringan dapat menurunkan hasil kebun. Fluktuasi produksi merupakan hal yang normal terutama di pertanian. Pada kondisi yang ekstrim, penurunan dan kenaikan produksi juga bisa ekstrim, jauh dari tingkat “normalnya”.</p>
<p>Di dalam banyak hal, nilai suatu pengukuran (produksi, konsumsi, tinggi badan, tingkat kepuasan,kecerdasan dll) sebagian besar berkumpul pada angka tertentu, kemudian proporsinya semakin mengecil ketika nilai-nilai itu semakin jauh dari nilai pemusatannya (<em>central value</em>). Jika digambarkan kita akan mendapatkan suatu kurva berbentuk genta (<em>bell-shape curve</em>), dimana proporsi data simetris berada di kanan dan kiri nilai tengah. Bentuk ini disebut dengan distribusi normal.</p>
<p>Sebagai ilustrasi kita akan menggunakan data produktivitas tanaman tomat di berbagai negara yang bisa diunduh di <a href="https://ourworldindata.org">ourworldindata</a>. Secara teoritis, produktivitas tomat dipengaruhi oleh banyak faktor: mutu bibit, manajemen budidaya, air, hama penyakit, kondisi cuaca dll yang semuanya mempengaruhi efesiensi fotosintesis tanaman tomat. Hal-hal yang dapat meningkatkan efisiensi fotosintesis, akan dapat meningkatkan produktivitas tanaman seperti yang dilakukan oleh para peneliti dari <em>University of Sussex</em> dalam artikel <a href="http://www.isaaa.org/kc/cropbiotechupdate/article/default.asp?ID=18262">ini</a>.</p>
<p>Data yang sudah diunduh, misalkan kita taruh di desktop dan kita beri nama tomat.dun.csv. Data ini selanjutnya kita masukkan ke dalam R dan kita beri nama tomat.dunia (tobat maksiat dunia).</p>
<pre class="r"><code>tomat.dunia &lt;- read.csv (&quot;C:\\Users\\Anna\\Documents\\tomat.dun.csv&quot;) # gunakan garis geblak ganda atau garing tunggal /.</code></pre>
<pre class="r"><code>str(tomat.dunia) #untuk melihat struktur data pada file tomat.dunia</code></pre>
<pre><code>## &#39;data.frame&#39;:    10609 obs. of  4 variables:
##  $ Entity: chr  &quot;Africa&quot; &quot;Africa&quot; &quot;Africa&quot; &quot;Africa&quot; ...
##  $ Code  : chr  &quot; &quot; &quot; &quot; &quot; &quot; &quot; &quot; ...
##  $ Year  : int  1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 ...
##  $ Yield : num  12.3 13 12.9 13.2 13.5 ...</code></pre>
<p>Selanjutnya kita akan mengekstrak data produktivitas tomat di beberapa negara secara acak. Untuk negara di belahan selatan kita ambil Argentina dan Australia. Sedangkan untuk negara di belahan utara kita ambil Jerman dan Perancis. R menyediakan paket (package) untuk memudahkan melakukan ini. Jadi kita instal dulu paket dplyr dengan perintah install.packages (“dplyr”).</p>
<p>install.packages(“dplyr”) #jangan lupa tanda petik ganda</p>
<p>Kita tunggu beberapa saat sampai instal selesai, kemudian kita panggil paket tersebut dengan perintah</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p>Berikut adalah perintah-perintah untuk mengekstrak data produktivitas tomat di empat negara:</p>
<pre class="r"><code>tomat.arg &lt;- filter(tomat.dunia, Entity==&quot;Argentina&quot;) %&gt;% select (Yield) %&gt;% unlist #untuk memilih data produktivitas tomat di Argentina</code></pre>
<pre class="r"><code>tomat.aus &lt;- filter(tomat.dunia, Entity==&quot;Australia&quot;) %&gt;% select (Yield) %&gt;% unlist #untuk memilih data produktivitas tomat di Australia

tomat.jer&lt;- filter(tomat.dunia, Entity==&quot;Germany&quot;) %&gt;% select (Yield) %&gt;% unlist #untuk memilih data produktivitas tomat di Jerman

tomat.prc &lt;- filter(tomat.dunia, Entity==&quot;France&quot;) %&gt;% select (Yield) %&gt;% unlist #untuk memilih data produktivitas tomat di Perancis</code></pre>
<p>Tanda %&gt;% adalah <em>pipe</em> untuk mengalirkan hasil dari perintah sebelumnya ke perintah selanjutnya. Data tomat.dunia kita filter dengan kriteria <em>Entity</em> (nama negara), kemudian hasilnya kita alirkan ke perintah selanjutnya yaitu memilih variabel <em>Yield</em> (produktivitas), kemudian hasilnya kita <em>unlist</em>.</p>
<p>Selanjutnya kita explorasi produktivitas tomat di negara-negara tersebut:</p>
<pre class="r"><code>summary (tomat.arg)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   13.88   18.33   23.79   26.96   38.41   39.85</code></pre>
<pre class="r"><code>sd(tomat.arg) #untuk mengetahui standar deviasi</code></pre>
<pre><code>## [1] 9.467531</code></pre>
<pre class="r"><code>summary (tomat.aus)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.75   22.70   33.68   37.98   50.04   80.65</code></pre>
<pre class="r"><code>sd(tomat.aus) </code></pre>
<pre><code>## [1] 17.13879</code></pre>
<pre class="r"><code>summary (tomat.jer)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   23.60   30.45   40.36  100.59  172.77  259.76</code></pre>
<pre class="r"><code>sd(tomat.jer) </code></pre>
<pre><code>## [1] 83.1932</code></pre>
<pre class="r"><code>summary (tomat.prc)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   20.05   35.20   64.59   78.21  118.37  188.84</code></pre>
<pre class="r"><code>sd(tomat.prc)</code></pre>
<pre><code>## [1] 47.8893</code></pre>
<p>Sekarang kita bandingkan produktivitas tomat Argentina dengan Australia. Data menunjukkan bahwa rata-rata produktivitas tomat di Australia (37.98 ton/ha) lebih tinggi daripada Argentina (26.96 ton/ha) tetapi keragaman (sd) di Australia lebih tinggi. Data ini bisa jadi menunjukkan bahwa produktivitas tomat di Australia lebih fluktuatif daripada Argentina. Mungkin hal ini disebabkan oleh faktor iklim gurun di Australia yang tidak dapat diprediksi seperti kekeringan, kebakaran hutan (ini hanya asumsi, kebenarannya harus dicek dilapangan).</p>
<p>Nah sekarang apa yang dapat kita lihat produktivitas tomat di negara Jerman dan Perancis, apa yang bisa kita simpulkan? Secara umum dapat dikatakan bahwa produktivitas tomat di negara Jerman dan Perancis jauh lebih tinggi dari produktivitas di negara Argentina dan Australia. Bagaimana dengan keragamannya? Apa yang bisa kita simpulkan?</p>
<p>Hmm, bagaimana dengan produktivitas tomat di Indonesia. Dengan perintah yang sama:</p>
<pre class="r"><code>tomat.idn &lt;- filter(tomat.dunia, Entity==&quot;Indonesia&quot;) %&gt;% select (Yield) %&gt;% unlist #untuk memilih data produktivitas tomat di Indonesia
summary(tomat.idn)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.412   3.198   5.139   7.702  12.290  18.139</code></pre>
<pre class="r"><code>sd(tomat.idn)</code></pre>
<pre><code>## [1] 5.378243</code></pre>
<p>Jika asumsikan bahwa data produktivitas tomat di Indonesia terdistribusi secara normal, kita bisa buat kurva normalnya dengan perintah</p>
<pre class="r"><code>curve (dnorm (x, 7.702, 5.378), from = 0.5, to = 18) #darimana angka 7.702 dan 5.378?</code></pre>
<p><img src="/post/2020-08-15-normal-di-era-new-normal_files/figure-html/unnamed-chunk-8-1.png" width="672" />
Di statistik kita mengenal aturan 68-95-97.5, yang menunjukkan bahwa untuk data yang terdistribusi normal, peluang suatu data akan berada pada 1, 2 dan 3 kali standar deviasi dari nilai tengahnya adalah sebesar 68, 95 dan 99,7 %. Jadi kita menanam tomat di Indonesia, peluang bahwa produktivitas tomat yang kita tanam berada antara 2.3 (7.7-5.4) - 13 (7.7+5.4) ton/ha adalah sebesar 68%.</p>
<p>Sekarang berapa peluang produktivitas tomat yang kita dapat akan sebesar 6-16 ton/ha?</p>
<pre class="r"><code>pnorm (16, 7.702, 5.378243)-pnorm (6, 7.702, 5.378243)</code></pre>
<pre><code>## [1] 0.5627438</code></pre>
<p>Jadi peluang mendapatkan produktivitas antara 6-16 ton/ha jika menanam tomat di Indonesia adalah sebesar 56%. Semakin sempit selangnya, misal 10-16 ton/ha, peluang akan semakin kecil, mengapa? Tentu saja ini hanya diatas kertas lho ya! Banyak faktor kondisi lokal yang ikut menentukan hasil tomat. Menanam tomat di Sukapura Bromo akan berbeda dengan menanamnya di Paiton yang pesisir.</p>
<p>Pertanyaan yang lebih menarik sebenarnya adalah mengapa produktivitas tomat di Indonesia jauh lebih rendah dibandingkan dengan negara-negara lain di atas? Ini menjadi tugas mahasiswa <a href="https://fp.upm.ac.id">Fakultas Pertanian UPM</a> untuk menjawab dan meningkatkan produktivitas tomat di Indonesia. Ayo riset riset riset! RRR!</p>

</div>

        <footer class="post-footer clearfix">
    
        <p class="post-tags">
            <span>Tagged:</span>
            
            
                <a href="/tags/uji-normalitas/">uji normalitas</a>, 
            
                <a href="/tags/statistika-deskriptif/">statistika deskriptif</a>, 
            
                <a href="/tags/tomat/">tomat</a>
            
        </p>
    

    <div class="share">
        
            <a class="icon-twitter" href="https://twitter.com/share?text=Normal%20di%20Era%20New%20Normal&url=%2f2020%2f08%2fnormal-di-era-new-normal%2f"
                onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                <i class="fa fa-twitter"></i>
                <span class="hidden">Twitter</span>
            </a>
        

        
            <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=%2f2020%2f08%2fnormal-di-era-new-normal%2f"
                onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                <i class="fa fa-facebook"></i>
                <span class="hidden">Facebook</span>
            </a>
        

        
            <a class="icon-google-plus" href="https://plus.google.com/share?url=%2f2020%2f08%2fnormal-di-era-new-normal%2f"
              onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
              <i class="fa fa-google-plus"></i>
                <span class="hidden">Google+</span>
            </a>
        
        
    </div>
</footer>

        
    <div class="comments">
        <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "hugo-tranquilpeak-theme" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>

    </article>
</div>

            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <div class="site-title-wrapper">
                    <h1 class="site-title">
                        <a title="bangtedy BLOG" href="/">bangtedy BLOG</a>
                    </h1>
                    <a class="button-square button-jump-top js-jump-top" href="#">
                        <i class="fa fa-angle-up"></i>
                    </a>
                </div>

                <p class="footer-copyright">
                    <span>&copy; 2020 / Powered by <a href="https://gohugo.io/">Hugo</a></span>
                </p>
                <p class="footer-copyright">
                    <span><a href="https://github.com/roryg/ghostwriter">Ghostwriter theme</a> By <a href="http://jollygoodthemes.com">JollyGoodThemes</a></span>
                    <span>/ <a href="https://github.com/jbub/ghostwriter">Ported</a> to Hugo By <a href="https://github.com/jbub">jbub</a></span>
                </p>
            </div>
        </footer>

        <script src="/js/jquery-1.11.3.min.js"></script>
        <script src="/js/jquery.fitvids.js"></script>
        <script src="/js/scripts.js"></script>
    </body>
</html>

